/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-09 05:54:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.bandtracker.hibernate.entity.User;
import org.bandtracker.hibernate.entity.Show;
import org.bandtracker.hibernate.entity.Booking;
import java.util.List;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1574351613000L));
    _jspx_dependants.put("jar:file:/Users/nicholaswhite/Documents/GitHub/csc499/Application/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BandTracker/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.bandtracker.hibernate.entity.Show");
    _jspx_imports_classes.add("org.bandtracker.hibernate.entity.User");
    _jspx_imports_classes.add("org.bandtracker.hibernate.entity.Booking");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("   padding-top: 75px;\r\n");
      out.write("}\r\n");
      out.write("td\r\n");
      out.write("{\r\n");
      out.write("    padding:0 15px 0 15px;\r\n");
      out.write("}\r\n");
      out.write("tr.bordered {\r\n");
      out.write("    border-top: 1px solid #384452;\r\n");
      out.write("    padding: 50px;\r\n");
      out.write("    border-spacing: 5em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title>BandTracker</title>\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Raleway:400,700,900|Lato:400,900\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap CSS File -->\r\n");
      out.write("  <link href=\"assets/lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Libraries CSS Files -->\r\n");
      out.write("  <link href=\"assets/lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/lib/prettyphoto/css/prettyphoto.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/lib/hover/hoverex-all.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Main Stylesheet File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("    Template Name: Solid\r\n");
      out.write("    Template URL: https://templatemag.com/solid-bootstrap-business-template/\r\n");
      out.write("    Author: TemplateMag.com\r\n");
      out.write("    License: https://templatemag.com/license/\r\n");
      out.write("  ======================================================= -->\r\n");
      out.write("  <!--\r\n");
      out.write("  You are NOT allowed to delete the credit link to TemplateMag with free version.\r\n");
      out.write("  You can delete the credit link only if you bought the pro version.\r\n");
      out.write("  Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/solid-bootstrap-business-template/\r\n");
      out.write("  Licensing information: https://templatemag.com/license/\r\n");
      out.write("  -->\r\n");
      out.write("  \r\n");
      out.write(" <!--\r\n");
      out.write("    <style>\r\n");
      out.write("        div.container {\r\n");
      out.write("            border: 1px solid red;\r\n");
      out.write("        }\r\n");
      out.write("        div.col-lg-8 {\r\n");
      out.write("        \tborder: 1px solid blue;\r\n");
      out.write("        }\r\n");
      out.write("        div.col-lg-4 {\r\n");
      out.write("        \tborder: 1px solid blue;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("-->\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

String username = null;
String userId = null;
String userType = null;
Cookie[] cookies = request.getCookies();
	if(cookies !=null){
		for(Cookie cookie : cookies){
			if(cookie.getName().equals("user"))
				username = cookie.getValue();
			if(cookie.getName().equals("userId"))
				userId = cookie.getValue();
			if(cookie.getName().equals("userType"))
				userType = cookie.getValue();
			
		}
	}
if(username == null) response.sendRedirect("login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- Fixed navbar -->\r\n");
      out.write("  <div class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"navbar-header\">\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\">BandTracker</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"navbar-collapse collapse navbar-right\">\r\n");
      out.write("        <ul class=\"nav navbar-nav\">\r\n");
      out.write("          ");
 if (userId != null) {
        	  
      out.write("<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/operation?page=goHome&userId=");
      out.print(userId);
      out.write("&userType=");
      out.print(userType);
      out.write("\">HOME</a></li>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("          ");
 if (userId != null && ! userType.toLowerCase().equals("fan")) {
        	  
      out.write("<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/operation?page=myBooking&userId=");
      out.print(userId);
      out.write("&userType=");
      out.print(userType);
      out.write("\">BOOKING</a></li>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("          ");
 if (userId != null && userType.toLowerCase().equals("bar")) { 
        	  
      out.write("<li><a href=\"");
      out.print( request.getContextPath());
      out.write("/operation?page=addShow&bar_id=");
      out.print(userId);
      out.write("\">HOST A SHOW</a></li>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("          <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/operation?page=upcomingShows\">UPCOMING SHOWS</a></li>\r\n");
      out.write("          <li><a href=\"search.jsp\">SEARCH</a></li>\r\n");
      out.write("          ");
 if (userId != null) { 
        	  
      out.write("\r\n");
      out.write("          <li class=\"dropdown\">\r\n");
      out.write("            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">ETC<b class=\"caret\"></b></a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("              <li><a href=\"editProfile.jsp\">MY PROFILE</a></li>\r\n");
      out.write("              <li><a href=\"about.jsp\">ABOUT</a></li>\r\n");
      out.write("              <li><a href=\"myMessages.jsp\">MESSAGES</a></li>\r\n");
      out.write("              <li><a href=\"myReviews.jsp\">REVIEWS</a></li>\r\n");
      out.write("              <li><a href=\"myHistory.jsp\">SHOW HISTORY</a></li>\r\n");
      out.write("              <li><a href=\"");
      out.print( request.getContextPath());
      out.write("/site?action=destroy\">LOGOUT</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          ");
}
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--/.nav-collapse -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
